### ISSUE TITLE
issue when running the example biplanar xgradient

### ISSUE THREAD

**Issue by skywo1f** [kev-m/pyCoilGen#68]
DEBUG:pyCoilGen.sub_functions.split_disconnected_mesh:Faces need be adjusted
DEBUG:pyCoilGen.sub_functions.split_disconnected_mesh:Faces need be adjusted
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.044046 seconds
Upsample the mesh by subdivision:
DEBUG:pyCoilGen.sub_functions.refine_mesh: - iteration_num_mesh_refinement: 1
DEBUG:pyCoilGen.sub_functions.refine_mesh: - Refining part 0
DEBUG:pyCoilGen.sub_functions.refine_mesh: - Refining part 1
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.001051 seconds
Parameterize the mesh:
DEBUG:pyCoilGen.sub_functions.parameterize_mesh: - 3D mesh is already planar
DEBUG:pyCoilGen.sub_functions.parameterize_mesh: - 3D mesh is already planar
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.003564 seconds
Define the target field:
DEBUG:pyCoilGen.sub_functions.define_target_field: - dbzdx_fun: 1
DEBUG:pyCoilGen.sub_functions.define_target_field: - dbzdy_fun: 0
DEBUG:pyCoilGen.sub_functions.define_target_field: - dbzdz_fun: 0
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.009006 seconds
Calculate mesh one ring:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.196097 seconds
Create the basis function container which represents the current density:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.566037 seconds
Calculate the sensitivity matrix:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 5.235103 seconds
Calculate the gradient sensitivity matrix:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 8.466866 seconds
Calculate the resistance matrix:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.402640 seconds
Optimize the stream function toward target field and secondary constraints:
INFO:pyCoilGen.sub_functions.stream_function_optimization:Optimising with Tikhonov regularisation.
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 3.755046 seconds
Calculate the potential levels for the discretization:
DEBUG:pyCoilGen.helpers.timing:Elapsed time: 0.001051 seconds
Generate the contours:
ERROR:__main__:Caught exception: module 'numpy' has no attribute 'warnings'
DEBUG:pyCoilGen.helpers.persistence:Saving solution to 'debug\biplanar_xgradient_09_exception.npy'

**Comment by kev-m** [comment]
More data:
Generate the contours:
ERROR:__main__:Caught exception: module 'numpy' has no attribute 'warnings'
DEBUG:pyCoilGen.helpers.persistence:Saving solution to 'debug\biplanar_xgradient_09_exception.pickle'
Traceback (most recent call last):
  File "c:\Dev\pyCoilGen_Testing\pyCoilGen\examples\biplanar_xgradient.py", line 51, in <module>
    result = pyCoilGen(log, arg_dict)
  File "C:\Dev\pyCoilGen_Testing\.venv\lib\site-packages\pyCoilGen\pyCoilGen_release.py", line 395, in pyCoilGen
    raise e
  File "C:\Dev\pyCoilGen_Testing\.venv\lib\site-packages\pyCoilGen\pyCoilGen_release.py", line 244, in pyCoilGen
    coil_parts = calc_contours_by_triangular_potential_cuts(coil_parts)  # 10
  File "C:\Dev\pyCoilGen_Testing\.venv\lib\site-packages\pyCoilGen\sub_functions\calc_contours_by_triangular_potential_cuts.py", line 103, in calc_contours_by_triangular_potential_cuts      
    np.warnings.filterwarnings('ignore')
  File "C:\Dev\pyCoilGen_Testing\.venv\lib\site-packages\numpy\__init__.py", line 361, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'warnings'

**Comment by kev-m** [comment]
np.warnings has been removed form numpy.
https://github.com/scikit-learn/scikit-learn/pull/23654

**Comment by kev-m** [comment]
Fixed in latest release (0.2.1)
https://github.com/kev-m/pyCoilGen/tree/release
