### ISSUE TITLE
.stl file dimensions

### ISSUE THREAD

**Issue by irecana** [kev-m/pyCoilGen#72]
Hi! I am using this repo to generate some gradient coils for my lab and it works amazing, so thank you for sharing! 

I only have an observation regarding the dimensions of the .stl files. The .stl files generated by the code (but also the ones in the folder Geometry_Data) are smaller than expected; when opened either in Fusion or in Maya they are 2 orders of magnitude smaller (e.g. cylinder of 500mm radius and 1500mm length appear as 5mm radius and 15 mm length). Same for the generated .stl files. 

So to correctly generate a cylinder of 150mm length and 4.5mm radius I had to set: 'cylinder_mesh_parameter_list': [15,4.5,30,30,1,0,0,0], as if they were in cm instead of m (as specified in the documentation). 
The problem is that now I have the doubt about all other input parameters (e.g. target_region_resolution, target_gradient_streangth ..): are they in m or cm?

I will appreciate your help, Thanks, 
Irene

**Comment by kev-m** [comment]
Hello!

Thank you for reaching out.

I have had a quick look at the data in the generated STL file, using both the 'create bi-planar mesh' and 'create cylinder mesh' and then converting the binary STL data to ASCII to visually examine the results.

What I see indicates that the results are in metres:

For example, for the the cylindrical mesh, created with `[1.5, 0.5, 20, 20, 1, 0, 0, 0]`
```
facet normal 0.0018353794 0.011588136 -0.0
  outer loop
    vertex 0.1545085 0.47552827 -0.75
    vertex -3.1720658e-18 0.5 -0.75
    vertex 0.1545085 0.47552827 -0.675
  endloop
endfacet
```

However, reading the definition of STL files[1], I see that the unit is not explicitly provided, and CAD/CAM systems are expected to ask.  The assumption that the typical unit is "mm" would be consistent with your experience.

So, for correct manufacture, it is critical to tell the CAD/CAM system that you are using that the STL unit is in metres, not mm.

As for all the other parameters, there is no unit conversion that takes place in the STL import or mesh creation, so all units will be self-consistent in the application - that is, everything is metres.

I hope that this helps you!

[1] https://en.wikipedia.org/wiki/STL_(file_format)#Other_fields

**Comment by kev-m** [comment]
I will update the documentation to make it clear that this software expects that STL files are in metres.

**Comment by irecana** [comment]
I understand! Thank you for your reply! 
I opened the files with another software (Blender) and in fact it was read as expected. So thank you for clarifying!
